### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by hawkoon** [ccd0/imageboards.json#12]
.

**Comment by hawkoon** [comment]
Edenchan & Openchan are long gone. Spacechan is dead too.
New: Spacestro.xyz (alt url: Astrochan.net)
16ch.nl

**Comment by hawkoon** [comment]
No really, Edenchan & Openchan have been offline a long time now and aren't coming back.
Also: you haven't added the original GlowChan yet which came long before the clearnet one: http://6oddffr7nmliu4hpaxb42gquo6ewvkxk7gecdtf2hsotwangbpwzz5ad.onion/

**Comment by ccd0** [comment]
The URL you gave for GlowChan doesn't work at the moment, but I'll add it if it starts working again.

The Spacechan clones haven't been down for a long time compared to normal imageboard downtimes, they've just been down a long time compared to their length of existence. I went ahead and removed them.

**Comment by hawkoon** [comment]
https://coronachan.xyz is back
http://coronayyjx6g65u72f2muefkhluh4r3ezmm7567zc3wyaoa3bm632zqd.onion/
