### ISSUE TITLE
9channel board software update

### ISSUE THREAD

**Issue by 9san** [ccd0/imageboards.json#15]
There is a new fork with a pretty big amount of changes from OpenIB. ~~It's not quite yet ready for 1.0 public release so I'm keeping the code hidden until release (shouldn't be too far away now), but~~ it is superior to OpenIB now with lots of security/bug/design fixes and new features. Big focus on design though, one look at 8kun would tell you why (it's **very** ugly in its current state).

https://github.com/9san/OpenIB-Reloaded
~~I've yet to upload any real changes to the github though.~~ 1.0 beta is released.

**Comment by ccd0** [comment]
Thanks, updated.
