### ISSUE TITLE
Why is Shittyboard.ga not in the list?

### ISSUE THREAD

**Issue by hawkoon** [ccd0/imageboards.json#23]
Is it because you are personal friends with the owner and he asked you to not include it in the list? That would be favoritism and would mean this list is compromised.

**Comment by hawkoon** [comment]
Shittyboard is now http://r410a.ga and ccd0 refuses to add it to the list because of a personal agreement with the owner.
**Imageboards.json is officially compromised.** Someone fork it and make a more objective version without favoritism please.

**Comment by ccd0** [comment]
Both are dead now.
