### ISSUE TITLE
add new spanish imageboard 

### ISSUE THREAD

**Issue by mithlardman** [ccd0/imageboards.json#34]
https://www.hispasexy.org/ Please add the sexy version of spanish imageboard hispachan, thanks for reading, and another spanish imageboard https://www.latinchan.org/

**Comment by PVNFU-28** [comment]
hispasexy es un tema complicado, porque si bien la mayoria de usuarios son anonimos, si eres modelo te permiten crearte una cuenta y postear con tu nombre y un tag de [modelo].

**Comment by ccd0** [comment]
Thanks, added.
