### ISSUE TITLE
Updates (again)

### ISSUE THREAD

**Issue by ghost** [ccd0/imageboards.json#43]
_I promised myself I wouldn't do this anymore, yet here I am._

<s>-nichan.net has "en" language too (their /int/ board)</s>
-risovach.ru is still not an imageboard
<s>-0chanru.net doesn't exist anymore</s>
<s>-2333chan has "en" language too (their /int/ board)</s>
<s>-2chen.moe has a homepage, no need to directly link to /all/</s>
-64chan is now a textboard
<s>-Acrimonie has "en" language too (their /int/ board)</s>
<s>-Alokal has "en" language too (their /int/ board)</s>
<s>-antares.chan has a clearweb URL: http://98.176.83.71/</s>
<s>-inch.esy.es is missing</s>
-Balkanchan's lynxchan.net mirror is no longer functional
<s>-bumblebuck.com has been offline for a long time</s>
<s>-Bunkerchan is missing its .onion mirror</s>
<s>-C-board has been offline for a long time</s>
<s>-Chan.org.il has "en" language too (their /goys/ board)</s>
<s>-Dch has been offline for a long time</s>
<s>-EvilChan is offline</s>
<s>-ezchan has been offline for a long time</s>
-fatchan has a Lokinet mirror
<s>-FrChan has "en" language too (their /int/ board)</s>
<s>-Herdchan has been offline for a long time</s>
<s>-IB.WTF has been offline for a long time</s>
<s>-ichan.net is offline</s>
<s>-/int/craft has been offline for a long time</s>
<s>-Keskustori is offline</s>
<s>-Kohlchan has "en" language too (their /int/ board)</s>
<s>-LastChan has been offline for a long time</s>
<s>-Livebunker is offline</s>
-Loistolauta runs on tinyib, not Vichan
<s>-magyarchan has "en" language too (their /i/ board)</s>
<s>-ManChan is offline</s>
<s>-nagadashi chan is missing 2 redirects</s>
-Kakashi Nenpo is mistakingly called "Nen"
-It is impossible to post on PookaChan, has been broken for a long time
<s>-RitaChan has a clearweb URL: http://elysia-medium.com/</s>
<s>-shinkuchan has been offline for ages</s>
<s>-Stevenchan doesn't allow anonymous, non-logged in users to post anymore</s>
<s>-Suomilauta (onion) is offline</s>
<s>-TF2chan's posting has been broken for ages now (captcha never loads)</s>
-Image posting on twchan has been broken for a long time now
<s>-unknownonline.me has been offline for a long time now, the site redirects to a commercial parking page</s>
-VHSCHAN's brchan.org mirror is offline
<s>-Ylilauta has "en" language too (their /international/ board)</s>
<s>-Yumechan requires an account to post</s>
<s>-Zoomerchan is offline</s>

**Comment by ccd0** [comment]
I don't think it makes sense to add "en" to every imageboard that has an international board, or to immediately remove boards the instant they goes down. Many of these have been addressed before.

**Comment by ccd0** [comment]
Crossing off already known dead sites, and addressed/deliberate/invalid issues.

**Comment by ccd0** [comment]
Some comments about deliberate stuff: I'm not convinced it always makes sense to list the ICANN domain as the primary in all instances (do we even know if it's controlled by the same people?). Don't want to track IPs when a domain that resolves to the IP is available even if not ICANN. Technically alternative DNS roots are "clearnet," just not something most people have installed. Regarding Meguca sites, it keeps things more consistent to link to /all/. Of course all of this is open to debate.

**Comment by ccd0** [comment]
New offline sites added to my list which I may make public so people can check if something's known already: #45
Sites with broken posting or broken image posting I'm holding off on until there's some discussion in #44

Thanks for the updates.

**Comment by ccd0** [comment]
Opened some issues for discussing whether we should change the current deliberate choices: #46 #47

**Comment by ghost** [comment]
As announced in December, 55chan is now dead and redirecting to Favelachan.

**Comment by ghost** [comment]
600chan has closed.
https://archive.vn/f6dem

**Comment by ghost** [comment]
RitaChan has closed.
https://archive.vn/CrKMd

**Comment by Mytsy** [comment]
Is this list still currently maintained?
