### ISSUE TITLE
Why is Yumechan still on the list?

### ISSUE THREAD

**Issue by ghost** [ccd0/imageboards.json#48]
You need an account to post, and the description of your list says: List of **registration-free** / anonymous imageboards in JSON format.

I already told you about this in https://github.com/ccd0/imageboards.json/issues/43 but you just crossed it off without doing anything about it. Pretty stupid.

**Comment by ccd0** [comment]
Slash means or.

**Comment by ccd0** [comment]
The main test is "anonymous," and registration-free is only there because some sites make you fill in a name field but let you fill it in with whatever you want, including "anonymous." Edited README.md to clarify it a little better.

**Comment by ghost** [comment]
An imageboard by nature doesn't require a user account to post. Yumechan is a forum modeled to look like an imageboard.
